# Generated by Django 3.2 on 2022-04-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220401_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url2',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
